### ISSUE TITLE
CLI - hot wallet implementation

### ISSUE THREAD

**Issue by 0xean** [shapeshift/rFOX#58]
https://github.com/shapeshift/rFOX/issues/46

Based on the findings above, its clear we are going to need to use a hot wallet style implementation to distribute RUNE. This ticket is a placeholder for that implementation that we will spec out further this week.

**Comment by 0xean** [comment]
### Step 1 on day 1 after epoch:
- dry run of script to produce distribution JSON and hash of JSON (should have metadata for epoch start and end)
- sanity checks (sum all outputs match input rune amount, etc)
- persist to IPFS, public verification, post on forum.


### Step 2 on distribution day (15 days after epoch ends or next weekday):
- prompt for ipfs hash for rewards for the epoch
- confirm the date in the hash is logical (matches last epoch based on current date)
- confirm with user the epoch number, start and end date, or other important meta data with users
- generate seed phrase, encrypted file store (use keystore file) and prompt user to also back up seed phrase using secondary secrets manager 
- output RUNE address (account 0) and the derivation path we used 
- WARN USERS TO NOT USE ADDRESS FOR ANY OTHER PURPOSE DUE TO TX SEQUENCING
- generate transaction to send RUNE from the DAO msig to the RUNE address generated above
  - msig signers sign transaction to fund RUNE address
- validate the balance of RUNE / listen for funding tx  is sufficient  before we kick off script
- generate all transactions
- sign all transactions and output to temp file in case of errors.  We can always retry transactions from this file, nonces can enforce the transactions that are already successfully executed so no risk in re-running all of them as long no shenanigans with the wallet
- broadcast RUNE transactions.  
- If errors occur, prompt users to re-run from saved temp file of signed transactions.
- persist tx hashes to IPFS and output ipfs hash to user for post to forum 


Design script so that its modular for error handling to pick up in different states, but allow the happy path for the msig signers to run it in one go.

**Comment by 0xean** [comment]
SANITY CHECK:

Does the sum of the earned rewards for the epoch match the expected amount of earned rewards (REWARD_RATE * seconds in epoch)

**Comment by 0xean** [comment]
- encode RUNE memo with metadata (epoch, staking address, ipfs hash of epoch)

**Comment by woodenfurniture** [comment]
> SANITY CHECK:
> 
> Does the sum of the earned rewards for the epoch match the expected amount of earned rewards (REWARD_RATE * seconds in epoch)

Very close when `REWARD_RATE` is divided by `WAD` - but not exactly possibly due to the jitter in the timestamps on the blocks. From my example, from block 216083216 to 216092990, using previous epoch end of 216083215 to calc `secondsInEpoch`:
* `totalRewardsEarned` (as aggregated by account): 2450999999873,
* `secondsInEpoch`: 2451,
* `REWARD_RATE`: 1e27/1e18 = 1000000000
* `REWARD_RATE * secondsInEpoch` = 2451000000000

When using epoch start timestamp to calc `secondsInEpoch`, we're further off the mark:
* `totalRewardsEarned` (as aggregated by account): 2450999999873,
* `secondsInEpoch`: 2450,
* `REWARD_RATE`: 1e27/1e18 = 1000000000
* `REWARD_RATE * secondsInEpoch` = 2450000000000
